### ISSUE TITLE
Test failures from generated tests involving a DateTime

### ISSUE THREAD

**Issue by domvernon** [redwoodjs/graphql#3493]
👋 Hi again. I have a pretty standard schema of:
```prisma
model User {
  id        Int        @id @default(autoincrement())
  uuid      String     @unique
  email     String     @unique
  createdAt DateTime   @default(now())
  updatedAt DateTime   @updatedAt
  UserRole  UserRole[]
}
```

When I use `yarn rw g sdl user --crud`, this generates the expected files, but there are unexpected results when running the given tests with no further modification.

For example:
```
users › creates a user

    expect(received).toEqual(expected) // deep equality

    Expected: "2021-10-01T21:24:13Z"
    Received: 2021-10-01T21:24:13.000Z

      26 |     expect(result.uuid).toEqual('String3084963')
      27 |     expect(result.email).toEqual('String1469123')
    > 28 |     expect(result.updatedAt).toEqual('2021-10-01T21:24:13Z')
         |                              ^
      29 |   })
      30 |
      31 |   scenario('updates a user', async (scenario: StandardScenario) => {

      at src/services/users/users.test.ts:28:30
```

This is easy to fix with something like `expect(result.updatedAt.toISOString()).toEqual('2021-10-01T21:24:13.000Z')`, and of course I'm sure you would be encouraging everyone to write their own tests, but I'm guessing this may trip a few people up if just relying on what gets generated. It seems to be a combination of how prisma is handling DateTime and how the Redwood [generator is working](https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/service/service.js#L52).

For context I'm running a postgres database with the latest Redwood release (I don't think this is specific to this version).

**Comment by jtoar** [comment]
Hey @domvernon, thanks for reporting this. The generated tests should definitely be passing out of the box, so even though we want users to write their own tests, that's only after they've customized things. They should start with green checks!

Would you be open to submitting a PR to fix this? It's a good one for hacktoberfest! No pressure though; me or one of the other core team members can submit a quick fix too

**Comment by domvernon** [comment]
I would definitely be up for this, although can't commit to it for at least a week - if someone wants to go ahead in the mean time and fix it they are very welcome to.

**Comment by dthyresson** [comment]
I ran into this similar issue and solved it by using `parseISO` from `date-fns`:

```ts
 import { parseISO } from 'date-fns'
 ...
  scenario('creates a movie', async () => {
    const result = await createMovie({
      input: {
        title: 'The Fog',
        tmdbId: 1,
        posterPath: 'jhpg',
        releasedOn: '1980-01-01T00:00:00Z',
      },
    })

    expect(result.title).toEqual('The Fog')
    expect(result.releasedOn).toEqual(parseISO('1980-01-01T00:00:00Z'))
  })
```

**Comment by esteban-url** [comment]
FYI, this is still happening out of the box on a completely new project with `create-redwood-app@2.2.3`

I think this is the culprit:
https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/service/service.js#L55

`.replace(/\.\d{3}/, '')` removes the trailing `.000`

### Proposed solution

Utilize the ISO8601 Date format in its entirety. It seems to me a more standard way to handle dates, especially since that's what the `toISOString` function on the [Date Object does](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString).

The PR would be:

1. edit `packages/cli/src/commands/generate/service/service.js` to remove `.replace(/\.\d{3}/, '')`  in line 55:

    ```js
      case 'DateTime':
          return new Date().toISOString()
    ```

1. edit `packages/cli/src/commands/generate/service/__tests__/scenario.test.js` line 154.  That way the test  asserts the iso8601 format in int entirety:

    ```js
        const iso8601Regex = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/
    ```
I am currently testing this solution. Does it make sense? is there anything I'm missing?

### reproduction steps:

This is the repo that I created to reproduce it:
https://github.com/esteban-url/date-test/commits/main    

These are the steps I followed:

1. create redwood app
    ```sh
    yarn create redwood-app test-date
    (...)
    success Installed "create-redwood-app@2.2.3"
    ```

1. edit `schema.prisma`

    ```prisma
    datasource db {
      provider = "sqlite"
      url      = env("DATABASE_URL")
    }
    
    generator client {
      provider      = "prisma-client-js"
      binaryTargets = "native"
    }
    
    model test {
      id    Int     @id @default(autoincrement())
      date DateTime
    }
    ```

1. create migration
   
    ```sh
     yarn rw prisma migrate dev
    ```

1. generate sdl

    ```sh
     yarn rw g sdl test  
    ```
this will give you a these two test (among others) in `tests.test.js` (i just realized this was not the smartest name for the model...)

```js
  scenario('creates a test', async () => {
    const result = await createTest({
      input: { date: '2022-09-01T00:21:58Z' },
    })

    expect(result.date).toEqual('2022-09-01T00:21:58Z')
  })

  scenario('updates a test', async (scenario) => {
    const original = await test({ id: scenario.test.one.id })
    const result = await updateTest({
      id: original.id,
      input: { date: '2022-09-02T00:21:58Z' },
    })
```

1. run tests

    ```sh
     yarn rw test api  
    ```
    ```sh
    FAIL   api  api/src/services/tests/tests.test.js
      ● tests › creates a test
    
        expect(received).toEqual(expected) // deep equality
    
        Expected: "2022-09-01T00:21:58Z"
        Received: 2022-09-01T00:21:58.000Z
    
          25 |     })
          26 |
        > 27 |     expect(result.date).toEqual('2022-09-01T00:21:58Z')
             |                         ^
          28 |   })
          29 |
          30 |   scenario('updates a test', async (scenario) => {
    
          at api/src/services/tests/tests.test.js:27:25
          at Object.<anonymous> (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:163:16)
    
      ● tests › updates a test
    
        expect(received).toEqual(expected) // deep equality
    
        Expected: "2022-09-02T00:21:58Z"
        Received: 2022-09-02T00:21:58.000Z
    
          35 |     })
          36 |
        > 37 |     expect(result.date).toEqual('2022-09-02T00:21:58Z')
             |                         ^
          38 |   })
          39 |
          40 |   scenario('deletes a test', async (scenario) => {
    
          at api/src/services/tests/tests.test.js:37:25
          at Object.<anonymous> (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:163:16)
    
     PASS   api  api/src/directives/requireAuth/requireAuth.test.js
     PASS   api  api/src/directives/skipAuth/skipAuth.test.js
    
    Test Suites: 1 failed, 2 passed, 3 total
    Tests:       2 failed, 6 passed, 8 total
    Snapshots:   0 total
    Time:        2.944 s
    Ran all test suites.
    ```
### ad-hoc solution

```js
// Solution A: create a new Date object and use it in the  assertion
  scenario('creates a test', async () => {
    const date = new Date('2022-09-01T00:21:58Z')
    const result = await createTest({
      input: { date },
    })

    expect(result.date).toEqual(date)
  })

// Solution B: create a new Date object every time you use it
  scenario('updates a test', async (scenario) => {
    const original = await test({ id: scenario.test.one.id })
    const result = await updateTest({
      id: original.id,
      input: { date: new Date('2022-09-01T00:21:58Z') },
    })

    expect(result.date).toEqual(new Date('2022-09-01T00:21:58Z'))
  })
```

**Comment by esteban-url** [comment]
the solution ended up being a bit different than what I expected. but there is a PR now! 🎉
