### ISSUE TITLE
prerender doesn't support Suspense

### ISSUE THREAD

**Issue by Tobbe** [redwoodjs/graphql#4008]
I was trying to prerender a page that uses `<Suspense>`, but got the following error message.

![image](https://user-images.githubusercontent.com/30793/147405442-f6ecea50-3c61-4299-8363-0a0d9b5a1a4d.png)

```
  ⠸ Building Web...
    Prerendering Web...

You can use `yarn rw prerender --dry-run` to debug

---------- Error rendering path "/spare-parts" ----------
Error: ReactDOMServer does not yet support Suspense.
    at ReactDOMServerRenderer.render (/Users/tobbe/dev/redwood/acm-store-rw/node_modules/react-dom/cjs/react-dom-server.node.development.js:3844:25)
    at ReactDOMServerRenderer.read (/Users/tobbe/dev/redwood/acm-store-rw/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/Users/tobbe/dev/redwood/acm-store-rw/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at runPrerender (/Users/tobbe/dev/redwood/acm-store-rw/node_modules/@redwoodjs/prerender/dist/runPrerender.js:54:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Task.task (/Users/tobbe/dev/redwood/acm-store-rw/node_modules/@redwoodjs/cli/dist/commands/prerender.js:106:35)
```

**Comment by Tobbe** [comment]
One possible solution to this might be https://github.com/FormidableLabs/react-ssr-prepass
