### ISSUE TITLE
Renaming a table seems to have gotten the logic to truncate the tables in test scenarios out of date

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/graphql#4535]
Renaming a table seems to have gotten the logic to truncate the tables in test scenarios out of date.

I renamed and migrated a table from Play to Guess and now

```
  ● guesses › returns all guesses


    Invalid `prisma.executeRaw()` invocation:


      Raw query failed. Code: `1`. Message: `no such table: Play`

      at cb (node_modules/@prisma/client/runtime/index.js:38703:17)
      at Proxy._request (node_modules/@prisma/client/runtime/index.js:40859:18)
      at teardown (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:93:7)
      at Object.<anonymous> (node_modules/@redwoodjs/testing/config/jest/api/jest.setup.js:188:3)
```

I think the `scenarioTeardown.json` needs to be somehow re-generated on a rename?

```
["PossibleMovie","Play","Movie","Player"]
```

Didn't  have `Guess` and so it tried to delete from Play which no longer exists in the db.

**Comment by thedavidprice** [comment]
Not critical, but really annoying

**Comment by dthyresson** [comment]
Note: This may have been an odd case where I had test watch running and because of that the command to rewrite the `scenarioTeardown.json` file failed.

Not 100% but that may have been the case.

**Comment by dthyresson** [comment]
Unable to reproduce. Closing.

**Comment by JustinAimiable** [comment]
We just ran into this exact issue when renaming a table. I'm not sure about recreating, but the solution for us was to delete the `scenarioTeardown.json` file

**Comment by AlejandroFrias** [comment]
Any updates on why a table rename doesn't auto-regenerate the `.redwood/teardownScenarios.json` and if this will be fixed? For now deleting the file works, and we've added to our CI the same `rm .redwood/teardownScenarios.json` so that regeneration is forced on every run.

**Comment by thedavidprice** [comment]
> Any updates on why a table rename doesn't auto-regenerate the .redwood/teardownScenarios.json and if this will be fixed?

I'm sure this is simply a missed case. I didn't work on scenarios, but we're always fighting against performance issues, which is likely the reason for caching.

Would welcome a PR to work towards a fix+improvement (no pressure). The reality for the core team right now is that we're heavily focused on the Bighorn epoch roadmap (redwoodjs.com/roadmap) from now through September and it's going to be a challenge for us to keep up with issues like this in the meantime.
