### ISSUE TITLE
Double data migration when deploying on Render

### ISSUE THREAD

**Issue by zygopleural** [redwoodjs/graphql#4906]
# Expected behaviour

With a setup of:
```yaml
buildCommand: yarn && yarn redwood build api
startCommand: yarn redwood deploy render api
```

I expect a deployment to Render to:
1. Install dependencies
2. Build the API package
3. Apply any outstanding schema migrations
4. Apply any outstanding data migrations

# What currently happens

It seems to be doing everything twice, though:
```shell
Mar 24 11:25:40 AM  $ /opt/render/project/src/node_modules/.bin/redwood build api
Mar 24 11:25:46 AM  [11:25:46] Generating Prisma Client... [started]
Mar 24 11:25:50 AM  [11:25:50] Generating Prisma Client... [completed]
Mar 24 11:25:50 AM  [11:25:50] Verifying graphql schema... [started]
Mar 24 11:25:50 AM  [11:25:50] Verifying graphql schema... [completed]
Mar 24 11:25:50 AM  [11:25:50] Building API... [started]
Mar 24 11:25:52 AM  [11:25:52] Building API... [completed]
Mar 24 11:25:53 AM  Done in 12.39s.
Mar 24 11:26:08 AM  ==> Uploading build...
Mar 24 11:26:48 AM  ==> Build successful 🎉
Mar 24 11:26:48 AM  ==> Deploying...
Mar 24 11:28:01 AM  ==> Detected Node version 16.13.2
Mar 24 11:28:01 AM  ==> Starting service with 'yarn redwood deploy render api'
Mar 24 11:28:02 AM  yarn run v1.22.5
Mar 24 11:28:02 AM  $ /opt/render/project/src/node_modules/.bin/redwood deploy render api
Mar 24 11:28:11 AM  Prisma schema loaded from api/db/schema.prisma
Mar 24 11:28:11 AM  Datasource "db": PostgreSQL database "XXXXX", schema "XXXXX" at "XXXXX"
Mar 24 11:28:12 AM  
Mar 24 11:28:12 AM  39 migrations found in prisma/migrations
Mar 24 11:28:12 AM  
Mar 24 11:28:13 AM  ==> Detected Node version 16.13.2
Mar 24 11:28:13 AM  ==> Starting service with 'yarn redwood deploy render api'
Mar 24 11:28:14 AM  yarn run v1.22.5
Mar 24 11:28:14 AM  $ /opt/render/project/src/node_modules/.bin/redwood deploy render api
Mar 24 11:28:12 AM  Applying migration `20220322145237_xxxxx`
Mar 24 11:28:12 AM  Applying migration `20220322152647_xxxxx`
Mar 24 11:28:12 AM  Applying migration `20220322163626_xxxxx`
Mar 24 11:28:12 AM  Applying migration `20220323102005_xxxxx`
Mar 24 11:28:12 AM  
Mar 24 11:28:12 AM  The following migrations have been applied:
Mar 24 11:28:12 AM  
Mar 24 11:28:12 AM  migrations/
Mar 24 11:28:12 AM    └─ 20220322145237_xxxxx/
Mar 24 11:28:12 AM      └─ migration.sql
Mar 24 11:28:12 AM    └─ 20220322152647_xxxxx/
Mar 24 11:28:12 AM      └─ migration.sql
Mar 24 11:28:12 AM    └─ 20220322163626_xxxxx/
Mar 24 11:28:12 AM      └─ migration.sql
Mar 24 11:28:12 AM    └─ 20220323102005_xxxxx/
Mar 24 11:28:12 AM      └─ migration.sql
Mar 24 11:28:12 AM  
Mar 24 11:28:12 AM  All migrations have been successfully applied.
Mar 24 11:28:14 AM  $ /opt/render/project/src/node_modules/.bin/rw dataMigrate up
Mar 24 11:28:23 AM  Prisma schema loaded from api/db/schema.prisma
Mar 24 11:28:23 AM  Datasource "db": PostgreSQL database "XXXXX", schema "XXXXX" at "XXXXX"
Mar 24 11:28:23 AM  
Mar 24 11:28:23 AM  39 migrations found in prisma/migrations
Mar 24 11:28:23 AM  
Mar 24 11:28:24 AM  
Mar 24 11:28:24 AM  No pending migrations to apply.
Mar 24 11:28:25 AM  $ /opt/render/project/src/node_modules/.bin/rw dataMigrate up
Mar 24 11:28:37 AM  [11:28:37] 20220321152734-xxxxx.ts [started]
Mar 24 11:28:38 AM  [11:28:38] 20220321152734-xxxxx.ts [started]
Mar 24 11:29:00 AM  [11:29:00] 20220321152734-xxxxx.ts [completed]
Mar 24 11:29:00 AM  
Mar 24 11:29:00 AM  1 data migration(s) completed successfully.
Mar 24 11:29:00 AM  
Mar 24 11:29:00 AM  Starting API Server...
Mar 24 11:29:00 AM  Loading server config from /opt/render/project/src/api/server.config.js
Mar 24 11:29:00 AM  
Mar 24 11:29:00 AM  Importing Server Functions... 
Mar 24 11:29:02 AM  Error in data migration: Unique constraint failed on the fields: (`version`)
Mar 24 11:29:02 AM  [11:29:02] 20220321152734-xxxxx.ts [completed]
Mar 24 11:29:02 AM  
Mar 24 11:29:02 AM  1 data migration(s) completed successfully.
Mar 24 11:29:02 AM  1 data migration(s) exited with errors.
Mar 24 11:29:02 AM  
Mar 24 11:29:02 AM  error Command failed with exit code 1.
Mar 24 11:29:02 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Mar 24 11:29:02 AM  /opt/render/project/src/node_modules/execa/lib/error.js:60
Mar 24 11:29:02 AM              error = new Error(message);
Mar 24 11:29:02 AM                      ^
Mar 24 11:29:02 AM  
Mar 24 11:29:02 AM  Error: Command failed with exit code 1: yarn rw dataMigrate up    at makeError (/opt/render/project/src/node_modules/execa/lib/error.js:60:11)    at Function.module.exports.sync (/opt/render/project/src/node_modules/execa/index.js:194:17)    at runApiCommands (/opt/render/project/src/node_modules/@redwoodjs/cli/dist/commands/deploy/render.js:80:35)    at Object.handler (/opt/render/project/src/node_modules/@redwoodjs/cli/dist/commands/deploy/render.js:94:5)    at /opt/render/project/src/node_modules/yargs/build/index.cjs:443:71    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
Mar 24 11:29:02 AM    shortMessage: 'Command failed with exit code 1: yarn rw dataMigrate up',
Mar 24 11:29:02 AM    command: 'yarn rw dataMigrate up',
Mar 24 11:29:02 AM    escapedCommand: '"yarn rw dataMigrate up"',
Mar 24 11:29:02 AM    exitCode: 1,
Mar 24 11:29:02 AM    signal: undefined,
Mar 24 11:29:02 AM    signalDescription: undefined,
Mar 24 11:29:02 AM    stdout: undefined,
Mar 24 11:29:02 AM    stderr: undefined,
Mar 24 11:29:02 AM    failed: true,
Mar 24 11:29:02 AM    timedOut: false,
Mar 24 11:29:02 AM    isCanceled: false,
Mar 24 11:29:02 AM    killed: false
Mar 24 11:29:02 AM  }
Mar 24 11:29:02 AM  error Command failed with exit code 1.
Mar 24 11:29:02 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

# Steps to reproduce

I'll setup a minimal repo if this isn't already a known issue or has already been solved in a later release of RedwoodJS 😬 

# Info
```
❯ yarn redwood info
yarn run v1.22.17
$ /Users/lee/Code/nous/monorepo/node_modules/.bin/redwood info

  System:
    OS: macOS 11.5.2
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.0 - /var/folders/42/lwp4lm_5415fc4jjqbldypmr0000gn/T/yarn--1648126506975-0.4904504173909112/node
    Yarn: 1.22.17 - /var/folders/42/lwp4lm_5415fc4jjqbldypmr0000gn/T/yarn--1648126506975-0.4904504173909112/yarn
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 99.0.4844.83
    Safari: 14.1.2
  npmPackages:
    @redwoodjs/core: 0.45.0 => 0.45.0

✨  Done in 1.71s.
```

**Comment by zygopleural** [comment]
FYI @callingmedic911

**Comment by callingmedic911** [comment]
Thanks for filling this @zygopleural! Do you have multiple instances running in production (where we have the problem) while staging has only one?

**Comment by zygopleural** [comment]
> Do you have multiple instances running in production

Good point, yeah we have `{ min: 2, max: 5 }`

**Comment by callingmedic911** [comment]
Seems like the release command runs for every instance. Currently, the suggested alternative is to use Docker with `RUN` or `CMD` 🤨. Not ideal. More details: https://community.render.com/t/release-command-for-db-migrations/247/10

@dac09 @thedavidprice do you think anything we can do about it?

**Comment by dac09** [comment]
Sucky that you're seeing this @zygopleural - but I have good news - both datamigrate and prisma migrate won't actually do anything if they have previously run successfully - hopefully that's what you're seeing. 

>  Maybe we move the migration part to buildCommand?

This seems like a sensible solution to me Mr. medic!

**Comment by zygopleural** [comment]
> both datamigrate and prisma migrate won't actually do anything if they have previously run successfully - hopefully that's what you're seeing.

Yeah they don't re-run and cause issues at DB level, but the exit code of 1 makes the deploy fail

**Comment by callingmedic911** [comment]
That seems about right but we don't want to run deploy again as startCommand then:
```diff
buildCommand: yarn && yarn redwood build api && yarn redwood prisma migrate deploy && yarn redwood dataMigrate up
-startCommand: yarn redwood deploy render api
+startCommand: ./node_modules/.bin/rw-server api
```

If the direct invoking bin doesn't work then maybe `yarn rw-server api`.

**Comment by dac09** [comment]
> I guess we can update current render settings to

Yup, and what you can do, as a workaround is skip the migrations on the deploy too, and use the build command like you suggested above

```diff
-startCommand: yarn redwood deploy render api
+startCommand: yarn redwood deploy render api --no-prisma --no-data-migrate
```

until we fix at the framework level - I think that's what Aditya was referring to.

**Comment by dac09** [comment]
By the way, I just remembered there was probably a reason the migration was moved to the start command - running out of memory on the builder - Render have very hard limits on the free plan, and I think the prisma migrate step can go just above their limit. Lets wait for DP to comment, because I know he still has nightmares about this.

**Comment by zygopleural** [comment]
> By the way, I just remembered there was probably a reason the migration was moved to the start command - running out of memory on the builder - Render have very hard limits on the free plan, and I think the prisma migrate step can go just above their limit. Lets wait for DP to comment, because I know he still has nightmares about this. 

Yeah I saw @thedavidprice issue from last month 👍🏼
