### ISSUE TITLE
Crash in graphql endpoint when using redwood record

### ISSUE THREAD

**Issue by kengreeff** [redwoodjs/graphql#5305]
Hi Guys, 

I am seeing this when deploying our app to vercel:

```
[POST] /api/graphql
15:07:05:64
2022-04-23T05:07:05.729Z	03f00ea2-056a-4e46-87d8-708c73969721	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Could not find a \"redwood.toml\" file, are you sure you're in a Redwood project?","stack":["Error: Could not find a \"redwood.toml\" file, are you sure you're in a Redwood project?","    at getConfigPath (/var/task/node_modules/@redwoodjs/internal/dist/paths.js:72:11)","    at getBaseDir (/var/task/node_modules/@redwoodjs/internal/dist/paths.js:84:34)","    at getPaths (/var/task/node_modules/@redwoodjs/internal/dist/paths.js:120:30)","    at Object.<anonymous> (/var/task/node_modules/@redwoodjs/record/dist/tasks/parse.js:39:66)","    at Module._compile (internal/modules/cjs/loader.js:1085:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","    at Module.load (internal/modules/cjs/loader.js:950:32)","    at Function.Module._load (internal/modules/cjs/loader.js:790:12)","    at Module.require (internal/modules/cjs/loader.js:974:19)","    at require (internal/modules/cjs/helpers.js:101:18)"]}
```

From what I can see, it looks like the code here:

```
// packages/record/src/tasks/parse.js

import { getPaths } from '@redwoodjs/internal'
```

calling this:

```
// packages/internal/src/paths.ts

export const getPaths = (BASE_DIR: string = getBaseDir()): Paths => {
  const routes = resolveFile(path.join(BASE_DIR, PATH_WEB_ROUTES)) as string
  const { schemaPath } = getConfig(getConfigPath(BASE_DIR)).api
  const schemaDir = path.dirname(schemaPath)
```

and in turn, this:

```
// packages/internal/src/paths.ts

export const getConfigPath = (
  cwd: string = process.env.RWJS_CWD ?? process.cwd()
): string => {
  const configPath = findUp(CONFIG_FILE_NAME, { cwd })
  if (!configPath) {
    throw new Error(
      `Could not find a "${CONFIG_FILE_NAME}" file, are you sure you're in a Redwood project?`
    )
  }
  return configPath
}

```

I am assuming that `redwood.toml` is not copied or built and therefore can never be found.

Not sure what the solution is for this one unfortunately but am happy to update if someone can point me in the right direction

**Comment by thedavidprice** [comment]
Looping in @cannikin

**Comment by cannikin** [comment]
Looping in @thedavidprice, this seems to be an issue with Vercel and this `RWJS_CMD` env var not existing? RedwoodRecord is just importing `getPaths` from `@redwoodjs/internal` and getting this error.

**Comment by kengreeff** [comment]
ahh interesting - is this something vercel need to fix or can we do it from within redwood?

**Comment by cannikin** [comment]
Well, I assume people have been deploying to Vercel successfully all this time, so I'm not sure what's different about RR when it would come to importing that file...

**Comment by kengreeff** [comment]
Yea, not sure to be honest. Maybe they aren't using RedwoodRecord? I removed it and have managed to deploy successfully

**Comment by jtoar** [comment]
@kengreeff I was able to reproduce this! I'm guessing it's because redwood record is more dynamic / does more things at runtime than services et al. I'll report back

**Comment by jtoar** [comment]
Updating before I forget: I tried a few things and couldn't deploy a simple example to Vercel or Netlify. I know RedwoodRecord is considered experimental, but I'd like to carve out some time to figure this out at some point.

Note that Netlify's error was different from Vercel's: `camelcase` was missing. That should be an easy fix, but it's possible that after I add `camelcase` something else will throw. It's probably worth using a combination of `yarn doctor` and `zip-it-and-ship-it` to figure out what's missing.

**Comment by kengreeff** [comment]
Anything I can do to assist?

**Comment by jtoar** [comment]
@kengreeff haven't had time to dig in so there's not an obvious next step yet, but if you're willing to dive into the framework there's plenty you can do! Heads up though: this seems like a hard issue. How do you feel about digging into 1) dependencies, build processes, deployment provider specific build processes?

**Comment by cannikin** [comment]
We talked about this in a meeting today and @dac09 thinks it's because there's a usage of `getPaths` that's happening at *run time* instead of *build time*. `getPaths` comes from `@redwoodjs/internal` which is a HUGE package, so big that deploys on certain providers won't even complete because the serverless functions won't accept a function that large, so it's stripped out and not included as an available dependency at run time.

I haven't had a chance to look at the code, but it could require a major refactor depending on how it's used. @aguscha333 did you end up getting your stuff deployed to Netlify after that datamodel file location fix?

**Comment by cannikin** [comment]
@dac09 Could it all come down to this line?

https://github.com/redwoodjs/redwood/blob/main/packages/record/src/index.js#L8

The functions in that `tasks/parse.js` file are only used by a couple of CLI commands. But is the fact that it's being re-exported `index.js` what's messing things up? If so then can I just update the `import` that's bringing in those functions and change the path from `@redwoodjs/record` to `@redwoodjs/record/tasks/parse`?
